### ISSUE TITLE
关于解绑的一系列问题遗留

### ISSUE THREAD

**Issue by KKMAMi** [wjdh-platform/wjdh-mini#9]

**Comment by KKMAMi** [comment]
房屋列表
1. 提交解绑申请后，刷新列表后台没有任何状态的返回
2. 解绑成功后的左滑删除缺少接口
3. 像后台提出了拆分绑定房屋和解绑房屋的列表进行拆分
房屋详情
1. 申请解绑的房屋详情是不是需要返回什么信息进行提示
2. 审核状态中的时候需要全部数据都由后台提供，前台不写死

**Comment by TonyHappyStyle** [comment]
已完成，拉取接口文档
